name: yet-another-agents-repository

services:
  workspace:
    build:
      context: ./container/workspace
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    hostname: workspace
    volumes:
      - ../:/workspace:consistent
      - ../.data-volumes/.claude:/home/dev-user/.claude:consistent
      - /run/user/1000/pulse:/run/user/1000/pulse
    environment:
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    networks:
      - local-network

networks:
  local-network:
    driver: bridge